### ISSUE TITLE
刷流插件无法工作

### ISSUE THREAD

**Issue by Austinwenyz** [InfinityPacer/MoviePilot-Plugins#9]
刷流插件在两天前无法工作，之前都是正常工作的，很奇怪。我尝试了官方版和低频版，均出现一样的问题。我尝试过重装MP，清除全部数据重新安装插件，结果仍然报错。

报错log：
INFO:    brushflowlowfreq - 开始执行刷流任务 ...
Job "站点刷流Brush服务 (trigger: date[2024-06-03 16:02:06 CST], next run at: 2024-06-03 16:02:06 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/brushflowlowfreq/__init__.py", line 2143, in brush
    pre_condition_passed, reason = self.__evaluate_pre_conditions_for_brush()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/brushflowlowfreq/__init__.py", line 2363, in __evaluate_pre_conditions_for_brush
    if config_value and check(config_value):
                        ^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/brushflowlowfreq/__init__.py", line 2342, in <lambda>
    ("maxdlcount", lambda config: self.__get_downloading_count() >= int(config),
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/brushflowlowfreq/__init__.py", line 3811, in __get_downloading_count
    return len(torrents) or 0
           ^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
INFO:    brushflowlowfreq - 开始检查刷流下载任务 ...
WARNING: brushflowlowfreq - 连接下载器出错，将在下个时间周期重试

**Comment by InfinityPacer** [comment]
`连接下载器出错，将在下个时间周期重试`
下载器连接不上，导致无法获取种子信息，可以尝试看MP主程序能否正常下载种子和仪表盘查看下载器速率

**Comment by Austinwenyz** [comment]
好的感谢！发现是我自己的远程QB下载机的frp崩了导致连不上QB。感谢解答！
